spring:
  config:
    activate:
      on-profile: observability
  jpa:
    properties:
      hibernate:
        generate_statistics: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always